#!/bin/bash
#PBS -j oe
#PBS -o logs/
#PBS -l nodes=1:ppn=8
#PBS -l mem=35Gb

module load gcc/6.2.0
module load STAR/2.5.3a

cd $RNASEQ_ROOT/data/intermediate

STAR --runThreadN 8 --genomeDir $GENOME_DIR --readFilesIn $input_file $input_file2 --outFilterType BySJout --outFilterMultimapNmax 20 --alignSJoverhangMin 8 --alignSJDBoverhangMin 1 --outFilterMismatchNmax 999 --outFilterMismatchNoverLmax 0.04 --alignIntronMin 20 --alignIntronMax 1000000 --alignMatesGapMax 1000000 --outFileNamePrefix $RNASEQ_ROOT/data/intermediate/"$input_file"_g37_1stpass
