#!/bin/bash
#PBS -N log.star_g37_2pass
#PBS -j oe
#PBS -l walltime=6:00:00
#PBS -l nodes=1:ppn=8
#PBS -l mem=45Gb

module load gcc/6.2.0
module load STAR/2.5.3a

cd /scratch/a.cri.mforde/sra_downloads

STAR --runThreadN 8 --genomeDir /scratch/a.cri.mforde/sra_downloads/g37/2pass --readFilesIn $input_file $input_file2 --outFilterType BySJout --outFilterMultimapNmax 20 --alignSJoverhangMin 8 --alignSJDBoverhangMin 1 --outFilterMismatchNmax 999 --outFilterMismatchNoverLmax 0.04 --alignIntronMin 20 --alignIntronMax 1000000 --alignMatesGapMax 1000000 --outSAMtype BAM Unsorted --outFileNamePrefix "$input_file"_g37_2ndpass
